// Pricing tiers (cents) and vehicle-to-tier mappings
// Prices stored in cents to avoid floating-point issues

const PRICING = {
  compact: {
    label: 'Compact',
    icon: '🚗',
    exterior: 4999, interior: 9999, combo: 12999,
    shampoo: 5000, claybar: 10000, polish: 20000, engine: 5000, deepclean: 5000,
  },
  midsize: {
    label: 'Mid-Size',
    icon: '🚙',
    exterior: 5999, interior: 11999, combo: 15599,
    shampoo: 6000, claybar: 12000, polish: 24000, engine: 5000, deepclean: 6000,
  },
  suv: {
    label: 'SUV / Crossover',
    icon: '🚙',
    exterior: 6999, interior: 13999, combo: 18199,
    shampoo: 7000, claybar: 14000, polish: 28000, engine: 6000, deepclean: 7000,
  },
  fullsize: {
    label: 'Full-Size / Truck',
    icon: '🛻',
    exterior: 7999, interior: 15999, combo: 20799,
    shampoo: 8000, claybar: 16000, polish: 32000, engine: 6000, deepclean: 8000,
  },
  oversized: {
    label: 'Oversized',
    icon: '🚐',
    exterior: 9499, interior: 18999, combo: 24699,
    shampoo: 9500, claybar: 19000, polish: 38000, engine: 7000, deepclean: 9500,
  },
};

// Known model-to-tier mappings (lowercase "make model" -> tier)
// Models not in this map will prompt the user to pick a size
const TIER_MAP = {
  // Compact
  'acura integra': 'compact', 'audi a3': 'compact', 'bmw 2 series': 'compact',
  'chevrolet bolt': 'compact', 'chevrolet bolt ev': 'compact', 'chevrolet bolt euv': 'compact',
  'chevrolet spark': 'compact', 'chevrolet sonic': 'compact',
  'fiat 500': 'compact', 'fiat 500x': 'compact',
  'ford fiesta': 'compact', 'ford focus': 'compact', 'ford maverick': 'compact',
  'honda civic': 'compact', 'honda fit': 'compact', 'honda hr-v': 'compact',
  'hyundai accent': 'compact', 'hyundai elantra': 'compact', 'hyundai ioniq': 'compact',
  'hyundai ioniq 5': 'compact', 'hyundai kona': 'compact', 'hyundai veloster': 'compact', 'hyundai venue': 'compact',
  'kia forte': 'compact', 'kia niro': 'compact', 'kia rio': 'compact', 'kia soul': 'compact',
  'mazda mazda3': 'compact', 'mazda 3': 'compact', 'mazda mx-5': 'compact', 'mazda mx-5 miata': 'compact',
  'mini cooper': 'compact', 'mini hardtop': 'compact',
  'mitsubishi mirage': 'compact', 'mitsubishi mirage g4': 'compact',
  'nissan kicks': 'compact', 'nissan leaf': 'compact', 'nissan sentra': 'compact', 'nissan versa': 'compact',
  'subaru crosstrek': 'compact', 'subaru impreza': 'compact', 'subaru brz': 'compact',
  'tesla model 3': 'compact',
  'toyota corolla': 'compact', 'toyota corolla cross': 'compact', 'toyota gr86': 'compact',
  'toyota gr corolla': 'compact', 'toyota prius': 'compact', 'toyota yaris': 'compact',
  'volkswagen golf': 'compact', 'volkswagen golf gti': 'compact', 'volkswagen jetta': 'compact',
  'volkswagen id.4': 'compact',

  // Mid-Size
  'acura tlx': 'midsize', 'audi a4': 'midsize', 'audi a5': 'midsize',
  'bmw 3 series': 'midsize', 'bmw 4 series': 'midsize',
  'chevrolet camaro': 'midsize', 'chevrolet malibu': 'midsize',
  'dodge charger': 'midsize', 'dodge challenger': 'midsize',
  'ford bronco sport': 'midsize', 'ford mustang': 'midsize', 'ford escape': 'midsize',
  'genesis g70': 'midsize', 'genesis g80': 'midsize',
  'honda accord': 'midsize', 'honda cr-v': 'midsize',
  'hyundai sonata': 'midsize', 'hyundai santa cruz': 'midsize', 'hyundai tucson': 'midsize',
  'infiniti q50': 'midsize', 'infiniti q60': 'midsize',
  'kia k5': 'midsize', 'kia seltos': 'midsize', 'kia sportage': 'midsize', 'kia ev6': 'midsize',
  'lexus is': 'midsize', 'lexus es': 'midsize', 'lexus nx': 'midsize',
  'mazda mazda6': 'midsize', 'mazda 6': 'midsize', 'mazda cx-5': 'midsize', 'mazda cx-30': 'midsize',
  'mercedes-benz c-class': 'midsize', 'mercedes-benz cla-class': 'midsize',
  'nissan altima': 'midsize', 'nissan maxima': 'midsize', 'nissan rogue': 'midsize', 'nissan rogue sport': 'midsize',
  'polestar 2': 'midsize', 'porsche 718': 'midsize',
  'subaru forester': 'midsize', 'subaru legacy': 'midsize', 'subaru outback': 'midsize',
  'tesla model 3 long range': 'midsize',
  'toyota camry': 'midsize', 'toyota rav4': 'midsize', 'toyota tacoma': 'midsize',
  'toyota gr supra': 'midsize', 'toyota crown': 'midsize',
  'volkswagen tiguan': 'midsize', 'volkswagen taos': 'midsize',
  'volvo s60': 'midsize', 'volvo v60': 'midsize',

  // SUV / Crossover
  'acura mdx': 'suv', 'acura rdx': 'suv',
  'audi q5': 'suv', 'audi q7': 'suv', 'audi q8': 'suv', 'audi e-tron': 'suv',
  'bmw x3': 'suv', 'bmw x5': 'suv', 'bmw x4': 'suv',
  'buick enclave': 'suv', 'buick envision': 'suv',
  'cadillac xt5': 'suv', 'cadillac xt6': 'suv',
  'chevrolet blazer': 'suv', 'chevrolet equinox': 'suv', 'chevrolet traverse': 'suv', 'chevrolet trailblazer': 'suv',
  'dodge durango': 'suv',
  'ford bronco': 'suv', 'ford edge': 'suv', 'ford explorer': 'suv',
  'genesis gv70': 'suv', 'genesis gv80': 'suv',
  'honda passport': 'suv', 'honda pilot': 'suv',
  'hyundai palisade': 'suv', 'hyundai santa fe': 'suv',
  'infiniti qx50': 'suv', 'infiniti qx60': 'suv',
  'jeep cherokee': 'suv', 'jeep grand cherokee': 'suv', 'jeep grand cherokee l': 'suv',
  'jeep wrangler': 'suv', 'jeep compass': 'suv', 'jeep renegade': 'suv',
  'kia sorento': 'suv', 'kia telluride': 'suv', 'kia carnival': 'suv',
  'lexus rx': 'suv', 'lexus gx': 'suv',
  'lincoln corsair': 'suv', 'lincoln nautilus': 'suv',
  'mazda cx-9': 'suv', 'mazda cx-50': 'suv', 'mazda cx-90': 'suv',
  'mercedes-benz gle-class': 'suv', 'mercedes-benz glc-class': 'suv',
  'nissan murano': 'suv', 'nissan pathfinder': 'suv',
  'subaru ascent': 'suv',
  'tesla model y': 'suv', 'tesla model x': 'suv',
  'toyota 4runner': 'suv', 'toyota highlander': 'suv', 'toyota venza': 'suv',
  'toyota grand highlander': 'suv',
  'volkswagen atlas': 'suv', 'volkswagen atlas cross sport': 'suv',
  'volvo xc60': 'suv', 'volvo xc90': 'suv', 'volvo xc40': 'suv',

  // Full-Size / Truck
  'cadillac escalade': 'fullsize', 'cadillac escalade esv': 'fullsize',
  'chevrolet colorado': 'fullsize', 'chevrolet silverado': 'fullsize',
  'chevrolet silverado 1500': 'fullsize', 'chevrolet suburban': 'fullsize', 'chevrolet tahoe': 'fullsize',
  'dodge ram 1500': 'fullsize',
  'ford expedition': 'fullsize', 'ford f-150': 'fullsize', 'ford f150': 'fullsize',
  'ford ranger': 'fullsize',
  'gmc acadia': 'fullsize', 'gmc sierra': 'fullsize', 'gmc sierra 1500': 'fullsize',
  'gmc yukon': 'fullsize', 'gmc yukon xl': 'fullsize', 'gmc canyon': 'fullsize',
  'honda ridgeline': 'fullsize',
  'jeep gladiator': 'fullsize', 'jeep grand wagoneer': 'fullsize', 'jeep wagoneer': 'fullsize',
  'land rover defender': 'fullsize', 'land rover range rover': 'fullsize',
  'land rover range rover sport': 'fullsize', 'land rover discovery': 'fullsize',
  'lexus lx': 'fullsize',
  'lincoln aviator': 'fullsize', 'lincoln navigator': 'fullsize',
  'nissan frontier': 'fullsize', 'nissan titan': 'fullsize',
  'ram 1500': 'fullsize',
  'rivian r1t': 'fullsize', 'rivian r1s': 'fullsize',
  'tesla cybertruck': 'fullsize',
  'toyota land cruiser': 'fullsize', 'toyota sequoia': 'fullsize', 'toyota tundra': 'fullsize',

  // Oversized
  'chevrolet silverado 2500': 'oversized', 'chevrolet silverado 2500hd': 'oversized',
  'chevrolet silverado 3500': 'oversized', 'chevrolet silverado 3500hd': 'oversized',
  'chevrolet express': 'oversized',
  'chrysler pacifica': 'oversized',
  'ford e-series': 'oversized', 'ford e-350': 'oversized', 'ford e-450': 'oversized',
  'ford excursion': 'oversized',
  'ford f-250': 'oversized', 'ford f-350': 'oversized', 'ford f250': 'oversized', 'ford f350': 'oversized',
  'ford super duty': 'oversized',
  'ford transit': 'oversized', 'ford transit connect': 'oversized',
  'gmc sierra 2500': 'oversized', 'gmc sierra 2500hd': 'oversized',
  'gmc sierra 3500': 'oversized', 'gmc sierra 3500hd': 'oversized',
  'gmc savana': 'oversized',
  'honda odyssey': 'oversized',
  'mercedes-benz sprinter': 'oversized',
  'nissan nv': 'oversized', 'nissan nv200': 'oversized', 'nissan nv3500': 'oversized',
  'ram 2500': 'oversized', 'ram 3500': 'oversized', 'ram promaster': 'oversized',
  'ram promaster city': 'oversized',
  'toyota sienna': 'oversized',
};
